Feature: JSON flatten
codeblessing/json-tools pull request #41
Opened 2022-01-08 11:31 UTC by jedrzejSmok

function  flattening nested JSON object and array

2022-01-15 19:53 UTC, codeblessing commented on src/main/java/pl/poznan/put/jsontools/rest/JsonToolsController.java
> +                        baseTransform = transform;
Add `break;` here.

2022-01-15 22:35 UTC, codeblessing approved these changes

2022-01-15 22:35 UTC, codeblessing commented on src/test/java/pl/poznan/put/jsontools/logic/JsonTransformRetainAttributesTest.java
> +    public void testRetainAttributes1(){
Why this change?

2022-01-16 14:35 UTC, pawelstrzelczyk requested changes
all good, please apply ctrl+alt+l to format the code

2022-01-17 10:39 UTC, pawelstrzelczyk approved these changes
lovely

2022-01-17 11:29 UTC, merged